<?php $this->placeholder('right-sidebar')->news = $this->latestNews(5) ?>
<div id="content-index">
  <div>
    <h2><?php echo $this->translate('Recent Artwork'); ?></h2>
  </div>
  <div>
    <h2><?php echo $this->translate('Recent Stories'); ?></h2>
  </div>
  <div>
    <h2><?php echo $this->translate('Recent Poetry'); ?></h2>
  </div>
  <div>
    <h2><?php echo $this->translate('Recent Music'); ?></h2>
  </div>
</div>
