<?php
$recentArtwork = $this->translate('site:index:Recent Artwork');
$recentStories = $this->translate('site:index:Recent Stories');
$recentPoetry = $this->translate('site:index:Recent Poetry');
$recentMusic = $this->translate('site:index:Recent Music');
?>
<?php $this->placeholder('right-sidebar')->news = $this->latestNews(5) ?>
<div id="content-index">
  <div>
    <h2><?php echo $recentArtwork; ?></h2>
  </div>
  <div>
    <h2><?php echo $recentStories; ?></h2>
  </div>
  <div>
    <h2><?php echo $recentPoetry; ?></h2>
  </div>
  <div>
    <h2><?php echo $recentMusic; ?></h2>
  </div>
</div>
