<?php
$postedBy = $this->translate('news:newsLatestNews:Posted by %1$s on %2$s');
?>
<div id="newsLatestNews">
  <h1 class="blockTitle"><span><?php echo $this->translate('news:newsLatestNews:Latest News');?></span></h1>
<?php foreach ($this->news as $news) : ?>
  <?php $lang = substr($news['locale'], 0, 2); ?>
  <div class="newsItem" id="news-<?php echo $news['id'];?>" lang="<?php echo $lang; ?>">
    <h2 class="newsTitle">
      <?php echo $news['title']; ?>
    </h2>
    <h3 class="newsInfo">
      <?php $username = $news['author']['username']; ?>
      <?php $date = new Zend_Date(strtotime($news['datePublished'])) ?>
      <?php $datePublished = $date->get(Zend_Date::DATE_MEDIUM) . ' ' . $date->get(Zend_Date::TIME_SHORT); ?>
      <?php vprintf($postedBy, array($username, $datePublished)) ?>
    </h3>
    <p class="newsContent">
      <?php echo $news['content']?>
    </p>
  </div>
<?php endforeach; ?>
</div>